name: Continuous Integration (CI)

## Run CI jobs on all branches by default
on:
  push:
  pull_request:


jobs:
  test:
    name: Run tests
    runs-on: ubuntu-22.04
    steps:
    - name: Check out the Git repository
      uses: actions/checkout@v4
    - name: Set up Java toolchain
      uses: actions/setup-java@v4
      with:
        distribution: "temurin"
        java-version: "21"
        cache: "gradle"
    - name: Add gradlew permission
      run: chmod +x gradlew
    - name: Install Google Chrome
      run: |
        sudo apt update
        sudo apt install -y google-chrome-stable
    - name: Install ChromeDriver
      run: |
        CHROME_VERSION=$(google-chrome --version | awk '{print $3}' | cut -d '.' -f 1)
        LATEST_CHROMEDRIVER_VERSION=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION")
        wget -q "https://chromedriver.storage.googleapis.com/${LATEST_CHROMEDRIVER_VERSION}/chromedriver_linux64.zip"
        unzip chromedriver_linux64.zip
        sudo mv chromedriver /usr/local/bin/
        rm chromedriver_linux64.zip
    - name: Verify ChromeDriver
      run: chromedriver --version
    - name: Run unit tests
      run: ./gradlew test